#! /bin/sh

# TODO set vim
# theme bg to
# terminal bg
# so we get
# transparency

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# wallpaper
feh --bg-fill ~/Downloads/Wallpapers/509074.jpg

# compositor - random set of flags, needs testing
compton --daemon --no-fading-openclose --no-fading-destroyed-argb --vsync opengl-swc --backend glx --blur-background --xrender-sync --xrender-sync-fence --glx-swap-method 3

# launcher
kupfer &
